apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  namespace: my-service-namespace
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: my-app
